/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BostonServicesAdminRouteImport } from './routes/boston-services-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BostonServicesAdminIndexRouteImport } from './routes/boston-services-admin/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as BostonServicesAdminServicesRouteImport } from './routes/boston-services-admin/services'
import { Route as BostonServicesAdminLoginRouteImport } from './routes/boston-services-admin/login'
import { Route as BostonServicesAdminQuotesIndexRouteImport } from './routes/boston-services-admin/quotes/index'
import { Route as BostonServicesAdminQuotesQuoteIdRouteImport } from './routes/boston-services-admin/quotes/$quoteId'

const BostonServicesAdminRoute = BostonServicesAdminRouteImport.update({
  id: '/boston-services-admin',
  path: '/boston-services-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BostonServicesAdminIndexRoute =
  BostonServicesAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BostonServicesAdminRoute,
  } as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const BostonServicesAdminServicesRoute =
  BostonServicesAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => BostonServicesAdminRoute,
  } as any)
const BostonServicesAdminLoginRoute =
  BostonServicesAdminLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => BostonServicesAdminRoute,
  } as any)
const BostonServicesAdminQuotesIndexRoute =
  BostonServicesAdminQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => BostonServicesAdminRoute,
  } as any)
const BostonServicesAdminQuotesQuoteIdRoute =
  BostonServicesAdminQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => BostonServicesAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boston-services-admin': typeof BostonServicesAdminRouteWithChildren
  '/boston-services-admin/login': typeof BostonServicesAdminLoginRoute
  '/boston-services-admin/services': typeof BostonServicesAdminServicesRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/boston-services-admin/': typeof BostonServicesAdminIndexRoute
  '/boston-services-admin/quotes/$quoteId': typeof BostonServicesAdminQuotesQuoteIdRoute
  '/boston-services-admin/quotes/': typeof BostonServicesAdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boston-services-admin/login': typeof BostonServicesAdminLoginRoute
  '/boston-services-admin/services': typeof BostonServicesAdminServicesRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/boston-services-admin': typeof BostonServicesAdminIndexRoute
  '/boston-services-admin/quotes/$quoteId': typeof BostonServicesAdminQuotesQuoteIdRoute
  '/boston-services-admin/quotes': typeof BostonServicesAdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boston-services-admin': typeof BostonServicesAdminRouteWithChildren
  '/boston-services-admin/login': typeof BostonServicesAdminLoginRoute
  '/boston-services-admin/services': typeof BostonServicesAdminServicesRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/boston-services-admin/': typeof BostonServicesAdminIndexRoute
  '/boston-services-admin/quotes/$quoteId': typeof BostonServicesAdminQuotesQuoteIdRoute
  '/boston-services-admin/quotes/': typeof BostonServicesAdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boston-services-admin'
    | '/boston-services-admin/login'
    | '/boston-services-admin/services'
    | '/services/$serviceId'
    | '/boston-services-admin/'
    | '/boston-services-admin/quotes/$quoteId'
    | '/boston-services-admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boston-services-admin/login'
    | '/boston-services-admin/services'
    | '/services/$serviceId'
    | '/boston-services-admin'
    | '/boston-services-admin/quotes/$quoteId'
    | '/boston-services-admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/boston-services-admin'
    | '/boston-services-admin/login'
    | '/boston-services-admin/services'
    | '/services/$serviceId'
    | '/boston-services-admin/'
    | '/boston-services-admin/quotes/$quoteId'
    | '/boston-services-admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BostonServicesAdminRoute: typeof BostonServicesAdminRouteWithChildren
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boston-services-admin': {
      id: '/boston-services-admin'
      path: '/boston-services-admin'
      fullPath: '/boston-services-admin'
      preLoaderRoute: typeof BostonServicesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boston-services-admin/': {
      id: '/boston-services-admin/'
      path: '/'
      fullPath: '/boston-services-admin/'
      preLoaderRoute: typeof BostonServicesAdminIndexRouteImport
      parentRoute: typeof BostonServicesAdminRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boston-services-admin/services': {
      id: '/boston-services-admin/services'
      path: '/services'
      fullPath: '/boston-services-admin/services'
      preLoaderRoute: typeof BostonServicesAdminServicesRouteImport
      parentRoute: typeof BostonServicesAdminRoute
    }
    '/boston-services-admin/login': {
      id: '/boston-services-admin/login'
      path: '/login'
      fullPath: '/boston-services-admin/login'
      preLoaderRoute: typeof BostonServicesAdminLoginRouteImport
      parentRoute: typeof BostonServicesAdminRoute
    }
    '/boston-services-admin/quotes/': {
      id: '/boston-services-admin/quotes/'
      path: '/quotes'
      fullPath: '/boston-services-admin/quotes/'
      preLoaderRoute: typeof BostonServicesAdminQuotesIndexRouteImport
      parentRoute: typeof BostonServicesAdminRoute
    }
    '/boston-services-admin/quotes/$quoteId': {
      id: '/boston-services-admin/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/boston-services-admin/quotes/$quoteId'
      preLoaderRoute: typeof BostonServicesAdminQuotesQuoteIdRouteImport
      parentRoute: typeof BostonServicesAdminRoute
    }
  }
}

interface BostonServicesAdminRouteChildren {
  BostonServicesAdminLoginRoute: typeof BostonServicesAdminLoginRoute
  BostonServicesAdminServicesRoute: typeof BostonServicesAdminServicesRoute
  BostonServicesAdminIndexRoute: typeof BostonServicesAdminIndexRoute
  BostonServicesAdminQuotesQuoteIdRoute: typeof BostonServicesAdminQuotesQuoteIdRoute
  BostonServicesAdminQuotesIndexRoute: typeof BostonServicesAdminQuotesIndexRoute
}

const BostonServicesAdminRouteChildren: BostonServicesAdminRouteChildren = {
  BostonServicesAdminLoginRoute: BostonServicesAdminLoginRoute,
  BostonServicesAdminServicesRoute: BostonServicesAdminServicesRoute,
  BostonServicesAdminIndexRoute: BostonServicesAdminIndexRoute,
  BostonServicesAdminQuotesQuoteIdRoute: BostonServicesAdminQuotesQuoteIdRoute,
  BostonServicesAdminQuotesIndexRoute: BostonServicesAdminQuotesIndexRoute,
}

const BostonServicesAdminRouteWithChildren =
  BostonServicesAdminRoute._addFileChildren(BostonServicesAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BostonServicesAdminRoute: BostonServicesAdminRouteWithChildren,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
